version: '3.11.5'

services:
  jupyterhub:
    build:
      context: ./jupyterhub  
      dockerfile: Dockerfile  
    image: my_remote_jupyterhub
    ports:
      - "8069:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub_data:/srv/jupyterhub/data

  lab:
    build:
      context: ./jupyterlab  
      dockerfile: Dockerfile  
    image: my_remote_jupyterlab


volumes:
  jupyterhub_data:

networks:
  jupyterhub:
    name: jupyterhub
