version: '3.11.5'

services:
  jupyterhub:
    build: .
    image: my_jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub_data:/srv/jupyterhub/data
    ports:
      - "8068:8000"
    networks:
      - jupyterhub

volumes:
  jupyterhub_data:

networks:
  jupyterhub:
    name: jupyterhub
